### PR TITLE
Add try statement on link display code to never break on invalid links

### PR DESCRIPTION
**Pull request by wolfcomp**
so team meeting incident on 02/24/2021 never happens again

### CODE REVIEW

**Comment by Chew** [comment]
Just parse out anything containing uwu or owo, will solve all of the problems!

**Comment by wolfcomp** [comment]
> Just parse out anything containing uwu or owo, will solve all of the problems!

noted make a function that you can toggle to make everything on the site owofied <.<

**Review by wolfcomp — COMMENTED** [review]
thanks credo i hate this

**Review by mja00 — APPROVED** [review]
I hate this thanks

**Comment by mja00** [comment]
Implemented in #488

**Pull request closed without merging**
