### PR TITLE
Feature/improve docker compose

### PR DESCRIPTION
**Pull request by Eein**
Outside of accidently purging whitespace from the readme, the following has been added and required testing:

Moved docker-compose.yml to docker-compose.prod.yml 
Updated docker-compose.yml to start all the necessary applications required to test on boot
Updated docker-compose to run the app minimally for local development - this can be exanded in the future to pull up the entire stack.

Required Changes:
- [x] Change development server from using docker-compose.yml to docker-compose.prod.yml

Required Docker-Compose Testing:
- [x] MacOS M1
- [x] WSL on windows
- [x] Windows Native (may work as well)
- [x] Linux Native (arch)

To test:

- Ensure you've brought all your containers and networks down by running `docker-compose down` twice
- Ensure you've created the database (might already exist)
```
docker-compose run app bash
app> mix ecto.create
```

run `docker-compose up` to make sure the server starts and the application is accesible from `localhost:4000` (use `docker-compose up --build` if you've built this container before)

To run tests:

run `docker-compose run app bash` and run `mix test` - there should be a complete passing suite with no errors

References Issue https://github.com/Glimesh/glimesh.tv/issues/632

### CODE REVIEW

**Comment by LukeHandle** [comment]
Not entirely surprising, but I had to force a build first (after I accidentally built using main branch).
`docker-compose up --build`


But, confirmed working on Ubuntu 20.04 in WSL2, with Docker Desktop (engine v20.10.5).

Was really easy compared to my fears of getting this working.

**Comment by mja00** [comment]
Tested on an M1 Macbook Air, running the [Apple Silicon build(3.3.1)](https://docs.docker.com/docker-for-mac/apple-silicon/) of Docker Desktop, engine v20.10.5. Everything created correctly, compiled fine for creating the database, and loading up the site. However, when running tests a few would timeout on `GenServer` calls, which seems to be either 1) an M1 Mac thing or 2) due to throttling of the MBA after 75c temps.

**Comment by Eein** [comment]
I did some tests at varying cpu limits in docker:
0.50 (half core) > ran slowly and passed
0.25 (quarter) > ran even slower and passed
0.15 (15% of a core) > ran EVEN slower and passed
0.10 (10% of a core) > had a drop from the ecto sandbox connection for 1 test, but picked back up and finished without error
0.01 (1% of a core) > had to afk for a while but came back to the database not being able to be created

My guess is that the throttling and platform specific behaviour around docker on the M1 mac caused the issue. I'd recommend trying again once it cools off, as the container itself shouldn't heat up your machine as much as a container build will. 

If you get a set of passing tests by running 
```bash
docker-compose run app bash
app> mix test
```
We can call it good :3

**Comment by LukeHandle** [comment]
I thought I'd do some more testing on Windows. Benchmark was the ~15 seconds reported test run (excludes the load/init) for pure WSL2.

1. WSL2 integration, *using Windows filesystem* via WSL2

Painfully slow, seems unlikely people would try this? Broken.
```
$ docker-compose run --rm app mix test
[...]

Finished in 57.3 seconds
530 tests, 11 failures
```

2. WSL2 integration, using Windows filesystem via PowerShell.

Seemed quicker, though reported slower. Broken.

<details><summary>Test failures</summary><p>

I trimmed some of the stacktraces - I could re-run if needed, but I guess we don't _really_ care.
```
  1) test GET /users/confirm renders the confirmation page (GlimeshWeb.UserConfirmationControllerTest)
     test/glimesh_web/controllers/user_confirmation_controller_test.exs:13
     ** (exit) exited in: GenServer.call(#PID<0.560.0>, {:lock, "Glimesh.BlogMigration.list_recent_posts()", #Reference<0.2004839407.2239234049.243200>}, 5000)
         ** (EXIT) time out
     code: conn = get(conn, Routes.user_confirmation_path(conn, :new))
     stacktrace:
[...]

  2) test GET /users/payments renders settings page (GlimeshWeb.UserPaymentsControllerTest)
     test/glimesh_web/controllers/user_payments_controller_test.exs:7
     ** (exit) exited in: GenServer.call(#PID<0.560.0>, {:lock, "Glimesh.BlogMigration.list_recent_posts()", #Reference<0.2004839407.2239234049.243263>}, 5000)
         ** (EXIT) time out
     code: conn = get(conn, Routes.user_payments_path(conn, :index))
     stacktrace:
[...]

  3) test GET /users/settings renders settings page (GlimeshWeb.UserSecurityControllerTest)
     test/glimesh_web/controllers/user_security_controller_test.exs:10
     ** (exit) exited in: GenServer.call(#PID<0.560.0>, {:lock, "Glimesh.BlogMigration.list_recent_posts()", #Reference<0.2004839407.2239234049.243285>}, 5000)
         ** (EXIT) time out
     code: conn = get(conn, Routes.user_security_path(conn, :index))
     stacktrace:
[...]

  4) test POST /users/log_in logs the user in with username (GlimeshWeb.UserSessionControllerTest)
     test/glimesh_web/controllers/user_session_controller_test.exs:43
     ** (exit) exited in: GenServer.call(#PID<0.560.0>, {:lock, "Glimesh.BlogMigration.list_recent_posts()", #Reference<0.2004839407.2239234055.241873>}, 5000)
         ** (EXIT) time out
     code: conn = get(conn, "/")
     stacktrace:
[...]

  5) test POST /users/register creates account and logs the user in (GlimeshWeb.UserRegistrationControllerTest)
     test/glimesh_web/controllers/user_registration_controller_test.exs:23
     ** (exit) exited in: GenServer.call(#PID<0.560.0>, {:lock, "Glimesh.BlogMigration.list_recent_posts()", #Reference<0.2004839407.2239234052.239494>}, 5000)
         ** (EXIT) time out
     code: conn = get(conn, "/")
     stacktrace:
[...]

13:55:52.211 [error] GenServer Glimesh.Workers.StreamMetrics terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.592.0>.

When using ownership, you must manage connections in one
of the four ways:
[...]

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:748: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (glimesh 0.1.0) lib/glimesh/workers/stream_metrics.ex:30: Glimesh.Workers.StreamMetrics.count_current_viewers/0
    (glimesh 0.1.0) lib/glimesh/workers/stream_metrics.ex:23: Glimesh.Workers.StreamMetrics.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :count_viewers

  6) test followers following firehose works (Glimesh.Api.SubscriptionTest)
     test/glimesh_web/api/subscription_test.exs:202
     Assertion failed, no matching message after 100ms
     The process mailbox is empty.
     code: assert_receive %Phoenix.Socket.Reply{ref: ^ref, status: :ok, payload: %{subscriptionId: subscription_id}}
     stacktrace:
       test/glimesh_web/api/subscription_test.exs:216: (test)

  7) test chat message subscriptions sending a chat message updates subscription (Glimesh.Api.SubscriptionTest)
     test/glimesh_web/api/subscription_test.exs:80
     Assertion failed, no matching message after 100ms
     The process mailbox is empty.
     code: assert_receive %Phoenix.Socket.Reply{ref: ^ref, status: :ok, payload: %{subscriptionId: subscription_id}}
     stacktrace:
       test/glimesh_web/api/subscription_test.exs:101: (test)

  8) test followers following subcription works (Glimesh.Api.SubscriptionTest)
     test/glimesh_web/api/subscription_test.exs:166
     Assertion failed, no matching message after 100ms
     The process mailbox is empty.
     code: assert_receive %Phoenix.Socket.Reply{ref: ^ref, status: :ok, payload: %{subscriptionId: subscription_id}}
     stacktrace:
       test/glimesh_web/api/subscription_test.exs:186: (test)

  9) test channel subscriptions updating channel title sends subscription update (Glimesh.Api.SubscriptionTest)
     test/glimesh_web/api/subscription_test.exs:9
     Assertion failed, no matching message after 100ms
     The process mailbox is empty.
     code: assert_receive %Phoenix.Socket.Reply{ref: ^ref, status: :ok, payload: %{subscriptionId: subscription_id}}
     stacktrace:
       test/glimesh_web/api/subscription_test.exs:27: (test)
```
</p>
</details>

```
Finished in 70.8 seconds
530 tests, 9 failures
```

3. WSL2 integration off (Linux VM in Hyper-V):

Fails immediately. Seems it can't see a file properly - unsure why. Broken.

```
PS C:\Users\lukeh\glimesh.tv> docker-compose run --rm app bash
Building app
Traceback (most recent call last):
  File "docker\utils\build.py", line 96, in create_archive
OSError: [Errno 22] Invalid argument: '\\\\?\\C:\\Users\\lukeh\\glimesh.tv\\assets\\node_modules\\.bin\\acorn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 202, in perform_command
  File "compose\metrics\decorator.py", line 18, in wrapper
  File "compose\cli\main.py", line 967, in run
  File "compose\cli\main.py", line 1428, in run_one_off_container
  File "compose\project.py", line 671, in up
  File "compose\service.py", line 365, in ensure_image_exists
  File "compose\service.py", line 1129, in build
  File "docker\api\build.py", line 159, in build
  File "docker\utils\build.py", line 29, in tar
  File "docker\utils\build.py", line 99, in create_archive
OSError: Can not read file in context: \\?\C:\Users\lukeh\glimesh.tv\assets\node_modules\.bin\acorn
[20560] Failed to execute script docker-compose
```

4. Windows containers fails due to lack of windows images (not surprising - and not remotely important).

**Comment by Eein** [comment]
Thank for the research! Looks like you ran into the same issues as @mja00 did on the m1 mac when using windows filesystem and powershell - this is usually because of how sandbox checkouts work - might be able to fix that one by doing some additional work on the conncase :)

**Comment by mja00** [comment]
After re-running the tests when the m1 mac cooled down it started with 2 tests failing, then the next test was 4, and then finally the 3rd test failed 6 tests. The time it took for the tests between the 1st and 3rd went from 28 seconds to 31.7 seconds, so there's definitely some weirdness going on with the apple silicon.

**Comment by Eein** [comment]
I'm going extract the M1 mac issue into a new ticket so it can be tested in isolation - otherwise all that needs to be done is the docker dev site deploy on DO would need to be moved to `docker-compose.prod.yml`

**Comment by Eein** [comment]
If the DO change is blocking merge, i'd be happy to move the DO dockerfile back to the standard file to prevent breakage, and move this dockerfile to something else and update the docs. :)

(just a note)

**Comment by mja00** [comment]
Sometimes clone gets busy and forgets about PRs so lemme just ping him. @clone1018 :)

**Comment by clone1018** [comment]
It looks like DigitalOcean App Platform just uses the normal Dockerfile and combines it with their own "docker-compose.yml" type system. No changes required :)! Testing locally now, will merge when it's done.

**Comment by clone1018** [comment]
I'm also getting test failures when running the command mentioned above. I did see the CPU usage spike up dramatically, ram was under control however. This is the computer I used to develop Glimesh on, but it's basically a potato still :)

Let me know if this expected and I'll go ahead with the merge.

image

image

**Comment by Eein** [comment]
This is expected, for now :) 

Since its happening on a non m1 mac its safe to assume theres some file performance issues. I actually have an older mbp i can start work on here!

**Pull request merged**
