### PR TITLE
Allow streamers to hide viewer count and viewers to default the viewer count to expanded/minimized

### PR DESCRIPTION
**Pull request by MemoryLeakDeath**
# Viewer Count Toggle
Based on a suggestion on [Building Glimesh](https://build.glimesh.tv/t/viewer-count-toggle/535).
Streamers would like the ability to hide the viewer count on their channel page.  I've increased the scope of this suggestion to also allow viewers to choose whether the viewer count (when visible) is expanded or minimized.

# New Settings
## Channel Settings
The channel owner can choose whether they want the viewer count to appear on their channel.  By default, the viewer count is on.

channel-settings

## Preferences page
Viewers can choose if they want the viewer count on all channels to display expanded (default) or be minimized.  Regardless of the setting users can still click the viewer count button to toggle it from expanded to minimized or vice versa.  Viewers cannot make the viewer count visible on channels that have hidden the count.

preferences

# Affects of the various settings
| Channel Owner Setting | Viewer Setting | Channel Page Result
|----------|----------|-----------|
| Show Viewer Count | Expand Viewer Count | visible-maximized
| Show Viewer Count | Minimize Viewer Count | visible-minimized
| Hide Viewer Count | Any Setting | hidden-not-followed hidden-followed

## Default settings
| Channel Owner Setting | Viewer Setting
|------|-----|
| Show Viewer Count (On) | Expand Viewer Count (On)

# Database Changes
- Added boolean column "show_viewer_count" to table "channels" with default true.
- Added boolean column "maximize_viewer_count" to table "user_preferences" with default true.

### CODE REVIEW

**Comment by clone1018** [comment]
If you can, rebase this against `dev` (the main branch) and the tests should magically pass.

**Comment by MemoryLeakDeath** [comment]
Rebasing complete, tests have passed.  Thanks again!

**Comment by MemoryLeakDeath** [comment]
Resolved merge conflicts.

**Comment by MemoryLeakDeath** [comment]
rebased with dev

**Comment by JamesMWestbrook** [comment]
Do we know when this will be pushed out to release? If you don't know it's fine, just It's getting kinda aggravating having to set it to not show viewer count every time I open up the web page, and that it defaults to showing the number.

**Comment by MemoryLeakDeath** [comment]
> Do we know when this will be pushed out to release? If you don't know it's fine, just It's getting kinda aggravating having to set it to not show viewer count every time I open up the web page, and that it defaults to showing the number.

Sorry, I don't know when.

**Comment by clone1018** [comment]
Allowing streamers to hide the viewer count is not currently aligned with our goals. Remembering view count hiding for users as a personal preference is a good idea. We can re-evaluate this when the beta is nearer to launch.

**Comment by JamesMWestbrook** [comment]
> 

Absolutely fine by me! I was moreso meaning the basic ability of anyone to hide that count for theirself, not hide it for other people and not give them a choice.

**Pull request closed without merging**
