### PR TITLE
Improved site footer

### PR DESCRIPTION
**Pull request by Ramireztime**
Improved site footer based on design posted in Discord. Should flow well on mobile as it's using bootstrap components. As mentioned in Discord thread, legibility may still be an issue with dark theme, although colors in this PR have been modified from original design.
**Note:** Blog links are not present because dev environment does not have any posts.

glimesh-dark
Desktop view [Dark]

glimesh-light
Desktop view [Light]

glimesh-mobile

### CODE REVIEW

**Comment by clone1018** [comment]
Hey @Ramireztime ! Thank you for the awesome contribution, glad to see new people helping out :D!

Just let me know when you're in a good place with this and we can review.

**Comment by Ramireztime** [comment]
Decided to swap out pattern for better legibility, but ultimately it's just a visual preference. Should be good to go, thanks again!

image

image

**Comment by clone1018** [comment]
This is looking great! First pass review:

* I think the Terms of Service | Privacy & Cookie Policy links should be a distinct color compared to the other text down there. They are extremely important documents and I think their current contrast on light & dark modes make them impossible to recognize as links.
* The dark mode footer links under Glimesh.tv are very hard to see against the dark background.

**Comment by Ramireztime** [comment]
Changed link colors to default to current link colors used throughout current site (looks to be bootstrap default). Legibility should be much better (not to mention when and if we theme those colors, there's less custom css to maintain). Also added hover state to social icons (uses secondary color).

image
image

**Comment by clone1018** [comment]
Looks great!

**Review by clone1018 — APPROVED** [review]

**Comment by clone1018** [comment]
Thanks for the work!

**Pull request merged**
