### PR TITLE
Allow http links with redirect uris

### PR DESCRIPTION
**Pull request by wolfcomp**
Fixes: #163

### CODE REVIEW

**Review by mja00 — APPROVED** [review]

**Comment by haydenmc** [comment]
I think we should restrict this exemption to only localhost redirects for desktop/native apps. 

We shouldn't encourage web apps to exchange creds over plaintext. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions

**Review by haydenmc — CHANGES_REQUESTED** [review]
I think we should restrict this exemption to only localhost redirects for desktop/native apps. 

We shouldn't encourage web apps to exchange creds over plaintext. 

Example:
https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions

**Comment by SaviorXTanren** [comment]
That's a fairly common practice I see and that's perfectly meets our requirements. As long as we're able to specify localhost and a specific port for it, that works. (EX: "http://localhost:8091")

**Comment by clone1018** [comment]
Added logic to ensure that you're only using an approved localhost url.

**Review by haydenmc — APPROVED** [review]

**Pull request merged**
