### PR TITLE
Mobile Chat Layout Changes

### PR DESCRIPTION
**Pull request by Ramireztime**
Changes placement of chat messages and chat input based on screen/display size. This should allow users to view stream and chat on mobile devices (although due to differences in screens and the [quirkiness of iOS](https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d), it's not 100% perfect).

image
**Desktop view**

image
**Mobile view** - input moved above messages

### CODE REVIEW

**Comment by Ramireztime** [comment]
Changed to draft as something interesting came up when you pop-out chat. Since it's pulling the same file for the popped out view, it will change how the user sees the chat UI. This affects all uses of the popped out chat (obs custom widgets, screen area captures, etc). Not a fan of changing those layouts, so may have to add another view just for popped out chat (have it ignore the reorder).

image

**Comment by mja00** [comment]
Awesome work @Ramireztime! Once you're ready for review again if you don't mind requesting me to review it on Github, it'll send me an email so I remember to do it. :P

**Comment by clone1018** [comment]
Hi @Ramireztime are you still interested in working on this?

**Comment by clone1018** [comment]
If your interest is re-piqued, feel free to reopen this PR!

**Pull request closed without merging**
